# ____________                           __________                __   __        __                              _____  
# \______  \  | _____  ___ __  __________\______   \_____ ________/  |_|__| ____ |  |   ____   ______     ___  __/  |  | 
# |     ___/  | \__  \<   |  |/ __ \_  __ \     ___/\__  \\_  __ \   __\  |/ ___\|  | _/ __ \ /  ___/     \  \/ /   |  |_
# |    |   |  |__/ __ \\___  \  ___/|  | \/    |     / __ \|  | \/|  | |  \  \___|  |_\  ___/ \___ \       \   /    ^   /
# |____|   |____(____  / ____|\___  >__|  |____|    (____  /__|   |__| |__|\___  >____/\___  >____  >       \_/\____   | 
#                    \/\/         \/                     \/                    \/          \/     \/                |__|

# Please excuse the cheesy ASCII Art

# ====================================================#
#                PlayerParticles Config               #
#      DO NOT DELETE OR EDIT THE FIELD "version"!     #
# ====================================================#

# Changing this value will reset your config on the next server reload/restart. 
# I don't recommend changing it
version: 4.3

# How many ticks to wait before spawning more particles
# Increasing this value may cause less lag (if there was any), but will decrease prettiness
# The lowest possible value is 1
# Going over 5 will likely look terrible
# Default: 1
ticks-per-particle: 1

# Check for new versions of the plugin
# Default: true
check-updates: true

# The worlds which this plugin is disabled in
# Remove the [] before you enter world names
# Default: []
disabled-worlds: []
#  - your_world_name_here
#  - add_more_under_these

# Max fixed effects per player
# Default: 5
max-fixed-effects: 5

# ================================================================ #
#                     MESSAGE CONFIGURATION                        #
# Important Notes:                                                 #
# * You can use the & symbol to color the messages                 #
# * {TYPE} Will be replaced with whatever that message requires    #
# * You can not use the apostrophe character! ( ' )                #
# ================================================================ #

# If you're using other plugins to execute commands you may wish to turn off messages
# Default: true
messages-enabled: true

# Whether or not to use the message-prefix field when displaying messages
# Default: true
use-message-prefix: true

# The prefix to use for all PlayerParticle messages
# This is useless if use-message-prefix is set to false
# Default: '&7[&3PlayerParticles&7]'
message-prefix: '&7[&3PlayerParticles&7]'

# ------------- #
#   Particles   #
# ------------- #

# No Particle Permission
# Default: '&cYou do not have permission to use &b{TYPE} &cparticles!'
message-no-permission: '&cYou do not have permission to use &b{TYPE} &cparticles!'

# /pp list No Particles
# Default: '&cYou do not have permission to use any particles!'
message-no-particles: '&cYou do not have permission to use any particles!'

# Now Using Particles
# Default: '&aNow using &b{TYPE} &aparticles!'
message-now-using: '&aNow using &b{TYPE} &aparticles!'

# Cleared Particles
# Default: '&aYour particles have been cleared!'
message-cleared-particles: '&aYour particles have been cleared!'

# Invalid Particle Type
# Default: '&cInvalid particle type! &b/pp effects'
message-invalid-type: '&cInvalid particle type! &b/pp effects &c| &b/pp effect <type>'

# Particle Command Usage
# You should not change the text here, only the coloring
# Default: '&b/pp effect <type>'
message-particle-usage: '&b/pp effect <type>'

# -------------- #
#     Styles     #
# -------------- #

# No Style Permission
# Default: '&cYou do not have permission to use the style type &b{TYPE}&c!'
message-no-permission-style: '&cYou do not have permission to use the style type &b{TYPE}&c!'

# /pp styles No Styles
# Default: '&cYou do not have permission to use any styles!'
message-no-styles: '&cYou do not have permission to use any styles!'

# Now Using Style
# Default: '&aNow using the style type &b{TYPE}&a!'
message-now-using-style: '&aNow using the style type &b{TYPE}&a!'

# Cleared Style
# Default: '&aYour style has been cleared!'
message-cleared-style: '&aYour style has been cleared!'

# Invalid Style Type
# Default: '&cInvalid style type! &b/pp styles &c| &b/pp style <type>'
message-invalid-type-style: '&cInvalid style type! &b/pp styles &c| &b/pp style <type>'

# Style Command Usage
# You should not change the text here, only the coloring
# Default: '&b/pp style <type>'
message-style-usage: '&b/pp style <type>'

# ------------ #
#     Data     #
# ------------ #

# Data Usage
# Default: '&eYour current effect requires &b{TYPE} &edata!'
message-data-usage: '&eYour current effect requires &b{TYPE} &edata!'

# No Data Required
# Default: '&eYour current effect does not use any data!'
message-no-data-usage: '&eYour current effect does not use any data!'

# Data Applied
# Default: '&aYour &b{TYPE} &adata has been applied!'
message-data-applied: '&aYour &b{TYPE} &adata has been applied!'

# Invalid Data Arguments
# Default: '&cInvalid &b{TYPE} &cdata arguments!'
message-data-invalid-arguments: '&cInvalid &b{TYPE} &cdata arguments!'

# Unknown Material
# Default: '&cThe {TYPE} name you supplied is invalid!'
message-data-material-unknown: '&cThe &b{TYPE} &cname you supplied is invalid!'

# Mismatched Material
# Default: '&cThe material supplied is not of type &b{TYPE}&c!'
message-data-material-mismatch: '&cThe material supplied is not of type &b{TYPE}&c!'

# Note Data Usage
# You should not change the text here, only the coloring
# Default: '&b/pp data <0-23>'
message-note-data-usage: '&b/pp data <0-23>'

# Color Data Usage
# You should not change the text here, only the coloring
# Default: '&b/pp data <0-255> <0-255> <0-255>'
message-color-data-usage: '&b/pp data [<0-255> <0-255> <0-255>] [rainbow]'

# Item Data Usage
# You should not change the text here, only the coloring
# Default: '&b/pp data <itemName> <0-15>'
message-item-data-usage: '&b/pp data <itemName> <0-15>'

# Block Data Usage
# You should not change the text here, only the coloring
# Default: '&b/pp data <blockName> <0-15>'
message-block-data-usage: '&b/pp data <blockName> <0-15>'

# ---------------- #
#     Prefixes     #
# ---------------- #

# You Can Use Particles
# Default: '&eYou can use:'
message-use: '&eYou can use:&b'

# Usage
# Default: '&eUsage:'
message-usage: '&eUsage:'

# Available Commands
# Default: '&eAvailable commands: &beffect, effects, style, styles, data, reset, worlds, version, help'
message-available-commands: '&eAvailable commands: &beffect, effects, style, styles, data, reset, worlds, version, help'

# Disabled Worlds
# Default: '&eParticles are disabled in these worlds:&b'
message-disabled-worlds: '&eParticles are disabled in these worlds:&b'

# ------------------ #
#   Alt. Execution
# ------------------ #

# Executed For Player
# Default: '&aCommand executed for &b{TYPE}'
message-executed-for-player: '&aCommand executed for &b{TYPE}'

# Failed Execute Not Found
# Default: '&cFailed to execute for &b{TYPE}&c! Player not found!'
message-failed-execute-not-found: '&cFailed to execute command for &b{TYPE}&c! Player not found!'

# Failed Execute No Permission
# Default: '&cFailed to execute for &b{TYPE}&c! You do not have permission!'
message-failed-execute-no-permission: '&cFailed to execute command for &b{TYPE}&c! You do not have permission!'

# ----------------- #
#   Fixed Effects
# ----------------- #

# No Permission Fixed
# Default: '&cYou do not have permission to use fixed effects!'
message-no-permission-fixed: '&cYou do not have permission to use fixed effects!'

# Reached Max Allowed
# Default: '&cYou have reached the maximum allowed fixed effects!'
message-max-fixed-effects-reached: '&cYou have reached the maximum allowed fixed effects!'

# Invalid Fixed Command
# Default: '&cInvalid sub-command for &b/pp fixed&c!'
message-invalid-fixed-command: '&cInvalid subcommand for &b/pp fixed&c! &eCommands: '

# Fixed Command Description For Create
# Default '&e/pp fixed create <x> <y> <z> <effect> <style> [data]'
message-fixed-command-desc-create: '&e/pp fixed create <x> <y> <z> <effect> <style> [data] - Creates a new fixed effect'

# Fixed Command Description For Remove
# Default: '&e/pp fixed remove <id>'
message-fixed-command-desc-remove: '&e/pp fixed remove <id> - Removes a fixed effect by its id'

# Fixed Command Description For List
# Default: '&e/pp fixed list - Lists all ids of your fixed effects'
message-fixed-command-desc-list: '&e/pp fixed list - Lists all ids of your fixed effects'

# Fixed Command Description For Information
# Default: '&e/pp fixed info <id> - Gets info on one of your fixed effects'
message-fixed-command-desc-info: '&e/pp fixed info <id> - Gets info on one of your fixed effects'


# ------------- #
#     Other     #
# ------------- #

# Reset
# Default: '&aYour effect, style, and data have all been reset!'
message-reset: '&aYour effect, style, and data have all been reset!'

# Invalid Arguments
# Default: '&cInvalid arguments! &a/pp help'
message-invalid-arguments: '&cInvalid arguments! &b/pp help'

# Disabled Worlds None
# Default: '&eParticles are not disabled in any worlds!'
message-disabled-worlds-none: '&eParticles are not disabled in any worlds!'

# Command Usage
# Default: '&eCommand Usage: /pp <command>'
message-command-usage: '&eCommand Usage: &b/pp <command>'

# ================================================================ #
#                     DATABASE CONFIGURATION                       #
# Information:                                                     #
# * This is meant for people who have multiple servers connected   #
#   together through BungeeCord. Unless you have multiple servers, #
#   it is recommended to keep the database storage disabled for    #
#   the best performance!                                          #
# ================================================================ #

# Enable Database
# Default: false
database-enable: false

# ------------------------------------------------------------------- #
# The following are only required if database-enable is set to 'true' #
# ------------------------------------------------------------------- #

# Database Hostname
# Default: ''
database-hostname: ''

# Database Port
# Default: 3306
database-port: 3306

# Database Name
# Default: ''
database-name: ''

# Database User Name
# Default: ''
database-user-name: ''

# Database User Password
# Default: ''
database-user-password: ''

# That's everything! You reached the end of the configuration
# Enjoy the plugin!