name: PlayerParticles
main: com.esophose.playerparticles.PlayerParticles
version: 4
description: Make particles around players.
author: Esophose
website: http://dev.bukkit.org/bukkit-plugins/playerparticles/
commands:
    pp:
        description: The main PlayerParticles command.